# Generated by Django 6.0.2 on 2026-02-23 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('start', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes (for placement and resize).')),
                ('entry_status', models.CharField(db_index=True, default='default', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['user', 'start'], name='calendar_ti_user_id_4a05a7_idx'), models.Index(fields=['project', 'start'], name='calendar_ti_project_dd1b73_idx')],
            },
        ),
    ]
